import { Press_Start_2P } from "next/font/google";
import Head from 'next/head';
import "./globals.css";

const press = Press_Start_2P({ subsets: ["latin"], weight: '400'});

export const metadata = {
  title: "Gamio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={press.className}>{children}</body>
    </html>
  );
}